name: myapp-test
services:
- name: web
  source_dir: /
  github:
    repo: your-username/myapp-test
    branch: main
  build_command: |
    composer install --no-dev --optimize-autoloader --no-interaction
    npm ci
    npm run build
    php artisan config:cache
    php artisan route:cache
    php artisan view:cache
  run_command: |
    php artisan migrate --force
    vendor/bin/heroku-php-nginx -C nginx.conf public/
  environment_slug: php
  instance_count: 1
  instance_size_slug: basic-xxs
  routes:
  - path: /
  health_check:
    http_path: /
  envs:
  - key: APP_ENV
    value: production
    scope: RUN_AND_BUILD_TIME
  - key: APP_DEBUG
    value: "false"
    scope: RUN_AND_BUILD_TIME
  - key: APP_KEY
    scope: RUN_AND_BUILD_TIME
    type: SECRET
  - key: DB_CONNECTION
    value: pgsql
    scope: RUN_AND_BUILD_TIME
  - key: DB_HOST
    value: ${db.HOSTNAME}
    scope: RUN_AND_BUILD_TIME
  - key: DB_PORT
    value: ${db.PORT}
    scope: RUN_AND_BUILD_TIME
  - key: DB_DATABASE
    value: ${db.DATABASE}
    scope: RUN_AND_BUILD_TIME
  - key: DB_USERNAME
    value: ${db.USERNAME}
    scope: RUN_AND_BUILD_TIME
  - key: DB_PASSWORD
    value: ${db.PASSWORD}
    scope: RUN_AND_BUILD_TIME
    type: SECRET
  - key: SESSION_DRIVER
    value: database
    scope: RUN_AND_BUILD_TIME
  - key: CACHE_STORE
    value: database
    scope: RUN_AND_BUILD_TIME
  - key: QUEUE_CONNECTION
    value: database
    scope: RUN_AND_BUILD_TIME
  - key: LOG_CHANNEL
    value: errorlog
    scope: RUN_AND_BUILD_TIME
databases:
- name: db
  engine: PG
  version: "15"
  size: db-s-dev-database
